-- CreateEnum
CREATE TYPE "type" AS ENUM (
    'NORMAL',
    'WATER',
    'FIRE',
    'GRASS',
    'PSYCHIC',
    'DARK',
    'GHOST',
    'STEEL',
    'FAIRY',
    'ELECTRIC',
    'POISON',
    'BUG',
    'FIGHTING',
    'ICE',
    'GROUND',
    'ROCK',
    'FLYING',
    'DRAGON'
);

-- CreateTable
CREATE TABLE "type_effectiveness" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "attacking_type" "type" NOT NULL,
    "defending_type" "type" NOT NULL,
    "effectiveness" DECIMAL(1, 1) NOT NULL,
    CONSTRAINT "type_effectiveness_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "type_effectiveness_attacking_type_defending_type_idx" ON "type_effectiveness"("attacking_type", "defending_type");

-- Populate the static type_effectiveness table
INSERT INTO
    type_effectiveness (
        attacking_type,
        defending_type,
        effectiveness
    )
VALUES
    -- NORMAL
    ('NORMAL', 'NORMAL', 1.0),
    ('NORMAL', 'WATER', 1.0),
    ('NORMAL', 'FIRE', 1.0),
    ('NORMAL', 'GRASS', 1.0),
    ('NORMAL', 'PSYCHIC', 1.0),
    ('NORMAL', 'DARK', 1.0),
    ('NORMAL', 'GHOST', 0.0),
    ('NORMAL', 'STEEL', 0.5),
    ('NORMAL', 'FAIRY', 1.0),
    ('NORMAL', 'ELECTRIC', 1.0),
    ('NORMAL', 'POISON', 1.0),
    ('NORMAL', 'BUG', 1.0),
    ('NORMAL', 'FIGHTING', 1.0),
    ('NORMAL', 'ICE', 1.0),
    ('NORMAL', 'GROUND', 1.0),
    ('NORMAL', 'ROCK', 0.5),
    ('NORMAL', 'FLYING', 1.0),
    ('NORMAL', 'DRAGON', 1.0),
    -- WATER
    ('WATER', 'NORMAL', 1.0),
    ('WATER', 'WATER', 0.5),
    ('WATER', 'FIRE', 2.0),
    ('WATER', 'GRASS', 0.5),
    ('WATER', 'PSYCHIC', 1.0),
    ('WATER', 'DARK', 1.0),
    ('WATER', 'GHOST', 1.0),
    ('WATER', 'STEEL', 1.0),
    ('WATER', 'FAIRY', 1.0),
    ('WATER', 'ELECTRIC', 1.0),
    ('WATER', 'POISON', 1.0),
    ('WATER', 'BUG', 1.0),
    ('WATER', 'FIGHTING', 1.0),
    ('WATER', 'ICE', 1.0),
    ('WATER', 'GROUND', 2.0),
    ('WATER', 'ROCK', 2.0),
    ('WATER', 'FLYING', 1.0),
    ('WATER', 'DRAGON', 0.5),
    -- FIRE
    ('FIRE', 'NORMAL', 1.0),
    ('FIRE', 'WATER', 0.5),
    ('FIRE', 'FIRE', 0.5),
    ('FIRE', 'GRASS', 2.0),
    ('FIRE', 'PSYCHIC', 1.0),
    ('FIRE', 'DARK', 1.0),
    ('FIRE', 'GHOST', 1.0),
    ('FIRE', 'STEEL', 2.0),
    ('FIRE', 'FAIRY', 1.0),
    ('FIRE', 'ELECTRIC', 1.0),
    ('FIRE', 'POISON', 1.0),
    ('FIRE', 'BUG', 2.0),
    ('FIRE', 'FIGHTING', 1.0),
    ('FIRE', 'ICE', 2.0),
    ('FIRE', 'GROUND', 1.0),
    ('FIRE', 'ROCK', 0.5),
    ('FIRE', 'FLYING', 1.0),
    ('FIRE', 'DRAGON', 0.5),
    -- GRASS
    ('GRASS', 'NORMAL', 1.0),
    ('GRASS', 'WATER', 2.0),
    ('GRASS', 'FIRE', 0.5),
    ('GRASS', 'GRASS', 0.5),
    ('GRASS', 'PSYCHIC', 1.0),
    ('GRASS', 'DARK', 1.0),
    ('GRASS', 'GHOST', 1.0),
    ('GRASS', 'STEEL', 0.5),
    ('GRASS', 'FAIRY', 1.0),
    ('GRASS', 'ELECTRIC', 1.0),
    ('GRASS', 'POISON', 0.5),
    ('GRASS', 'BUG', 0.5),
    ('GRASS', 'FIGHTING', 1.0),
    ('GRASS', 'ICE', 1.0),
    ('GRASS', 'GROUND', 2.0),
    ('GRASS', 'ROCK', 2.0),
    ('GRASS', 'FLYING', 0.5),
    ('GRASS', 'DRAGON', 0.5),
    -- PSYCHIC
    ('PSYCHIC', 'NORMAL', 1.0),
    ('PSYCHIC', 'WATER', 1.0),
    ('PSYCHIC', 'FIRE', 1.0),
    ('PSYCHIC', 'GRASS', 1.0),
    ('PSYCHIC', 'PSYCHIC', 0.5),
    ('PSYCHIC', 'DARK', 0.0),
    ('PSYCHIC', 'GHOST', 1.0),
    ('PSYCHIC', 'STEEL', 0.5),
    ('PSYCHIC', 'FAIRY', 1.0),
    ('PSYCHIC', 'ELECTRIC', 1.0),
    ('PSYCHIC', 'POISON', 2.0),
    ('PSYCHIC', 'BUG', 1.0),
    ('PSYCHIC', 'FIGHTING', 2.0),
    ('PSYCHIC', 'ICE', 1.0),
    ('PSYCHIC', 'GROUND', 1.0),
    ('PSYCHIC', 'ROCK', 1.0),
    ('PSYCHIC', 'FLYING', 1.0),
    ('PSYCHIC', 'DRAGON', 1.0),
    -- DARK
    ('DARK', 'NORMAL', 1.0),
    ('DARK', 'WATER', 1.0),
    ('DARK', 'FIRE', 1.0),
    ('DARK', 'GRASS', 1.0),
    ('DARK', 'PSYCHIC', 2.0),
    ('DARK', 'DARK', 0.5),
    ('DARK', 'GHOST', 2.0),
    ('DARK', 'STEEL', 1.0),
    ('DARK', 'FAIRY', 0.5),
    ('DARK', 'ELECTRIC', 1.0),
    ('DARK', 'POISON', 1.0),
    ('DARK', 'BUG', 1.0),
    ('DARK', 'FIGHTING', 0.5),
    ('DARK', 'ICE', 1.0),
    ('DARK', 'GROUND', 1.0),
    ('DARK', 'ROCK', 1.0),
    ('DARK', 'FLYING', 1.0),
    ('DARK', 'DRAGON', 1.0),
    -- GHOST
    ('GHOST', 'NORMAL', 0.0),
    ('GHOST', 'WATER', 1.0),
    ('GHOST', 'FIRE', 1.0),
    ('GHOST', 'GRASS', 1.0),
    ('GHOST', 'PSYCHIC', 2.0),
    ('GHOST', 'DARK', 0.5),
    ('GHOST', 'GHOST', 2.0),
    ('GHOST', 'STEEL', 1.0),
    ('GHOST', 'FAIRY', 1.0),
    ('GHOST', 'ELECTRIC', 1.0),
    ('GHOST', 'POISON', 1.0),
    ('GHOST', 'BUG', 1.0),
    ('GHOST', 'FIGHTING', 1.0),
    ('GHOST', 'ICE', 1.0),
    ('GHOST', 'GROUND', 1.0),
    ('GHOST', 'ROCK', 1.0),
    ('GHOST', 'FLYING', 1.0),
    ('GHOST', 'DRAGON', 1.0),
    -- STEEL
    ('STEEL', 'NORMAL', 1.0),
    ('STEEL', 'WATER', 0.5),
    ('STEEL', 'FIRE', 0.5),
    ('STEEL', 'GRASS', 1.0),
    ('STEEL', 'PSYCHIC', 1.0),
    ('STEEL', 'DARK', 1.0),
    ('STEEL', 'GHOST', 1.0),
    ('STEEL', 'STEEL', 0.5),
    ('STEEL', 'FAIRY', 2.0),
    ('STEEL', 'ELECTRIC', 0.5),
    ('STEEL', 'POISON', 1.0),
    ('STEEL', 'BUG', 1.0),
    ('STEEL', 'FIGHTING', 1.0),
    ('STEEL', 'ICE', 2.0),
    ('STEEL', 'GROUND', 1.0),
    ('STEEL', 'ROCK', 2.0),
    ('STEEL', 'FLYING', 1.0),
    ('STEEL', 'DRAGON', 1.0),
    -- FAIRY
    ('FAIRY', 'NORMAL', 1.0),
    ('FAIRY', 'WATER', 1.0),
    ('FAIRY', 'FIRE', 0.5),
    ('FAIRY', 'GRASS', 1.0),
    ('FAIRY', 'PSYCHIC', 1.0),
    ('FAIRY', 'DARK', 2.0),
    ('FAIRY', 'GHOST', 1.0),
    ('FAIRY', 'STEEL', 0.5),
    ('FAIRY', 'FAIRY', 1.0),
    ('FAIRY', 'ELECTRIC', 1.0),
    ('FAIRY', 'POISON', 0.5),
    ('FAIRY', 'BUG', 1.0),
    ('FAIRY', 'FIGHTING', 2.0),
    ('FAIRY', 'ICE', 1.0),
    ('FAIRY', 'GROUND', 1.0),
    ('FAIRY', 'ROCK', 1.0),
    ('FAIRY', 'FLYING', 1.0),
    ('FAIRY', 'DRAGON', 2.0),